#this is a service yml for services in kubernetes 
apiVersion: v1
kind: Service
metadata:
  name: kubernetes service 
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
